# Generated by Django 3.2 on 2022-12-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('question1_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question1_no_reason', models.TextField(blank=True, null=True)),
                ('question1_yes_reason', models.TextField(blank=True, null=True)),
                ('question2_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question2_no_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('question3_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question3_no_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('question4_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question5_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question6_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('captured_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
